import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from '@/components/providers/theme-provider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { StateProvider } from '@/context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Quotegraphy',
  description: 'Generated by Rishi',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(inter.className, 'bg-white dark:bg-[#313338]')}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            storageKey="quote-generator-theme"
            disableTransitionOnChange
          >
            <StateProvider>
              {children}
            </StateProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}